version: "3.9"
services:
  db:
    image: postgres:16
    container_name: bastion_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bastion_sudak
    ports:
      - "5432:5432"
    volumes:
      - bastion_pg:/var/lib/postgresql/data
volumes:
  bastion_pg:
